Fixed sound input issues and improved the documentation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,7 +7,7 @@ while [ -z "$USER" ]; do
 done
 
 echo "Installing core packages for system setup..."
-doas apk add linux-firmware iwd openresolv sway swaybg grim slurp clipman pipewire pipewire-pulse wireplumber flatpak bubblewrap man-db || { echo "Installation failed! Exiting."; exit 1; }
+doas apk add linux-firmware iwd openresolv sway swaybg grim slurp clipman pipewire pipewire-pulse pipewire-echo-cancel wireplumber flatpak bubblewrap man-db || { echo "Installation failed! Exiting."; exit 1; }
 doas apk add htop pamixer foot cargo firefox || echo "Failed to install extra tools!"
 
 echo "Do you need Bluetooth management? (yes/no)"
